title: Graphkt
description: A GraphQL kotlin server
theme: just-the-docs

url: https://cufyorg.github.io/graphkt-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
