title: Graphkt
description: A GraphQL kotlin server
theme: just-the-docs

url: https://graphkt.cufyorg.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
